# Issue #870 拡張予測システム設定
# 30-60%の予測精度向上を実現する統合予測システムの設定

enhanced_prediction:
  # システム全体設定
  system:
    mode: "auto"  # auto, enhanced, legacy, hybrid
    fallback_to_legacy: true
    enable_metrics: true
    enable_logging: true

  # 特徴量選択システム設定
  feature_selection:
    enabled: true
    max_features: 50
    min_importance_threshold: 0.01
    stability_threshold: 0.5
    correlation_threshold: 0.95
    information_gain_threshold: 0.1
    regime_adaptivity: true

    # 選択手法設定
    methods:
      - "mutual_info"
      - "lasso"
      - "rfe"
      - "permutation"
      - "variance"

    # アンサンブル選択設定
    ensemble_selection:
      min_votes: 2  # 過半数投票の最小票数
      voting_threshold: 0.5

  # アンサンブルシステム設定
  ensemble:
    enabled: true
    method: "adaptive"  # stacking, blending, voting, dynamic_weight, adaptive
    cv_folds: 5
    meta_model_type: "ridge"  # ridge, linear, elastic
    blend_ratio: 0.8
    min_weight: 0.01
    max_weight: 0.5
    weight_decay: 0.95
    performance_window: 20
    update_frequency: 10

    # ベースモデル設定
    base_models:
      tree_based:
        - "random_forest"
        - "gradient_boosting"
        - "extra_trees"
        - "ada_boost"
      linear:
        - "ridge"
        - "lasso"
        - "elastic_net"
        - "bayesian_ridge"
        - "huber"
      neural_network:
        - "mlp"
      neighbor_based:
        - "knn"
      svm_based:
        - "svr"

  # ハイブリッド時系列予測設定
  hybrid_timeseries:
    enabled: true

    # 状態空間モデル設定
    state_space:
      n_states: 4
      observation_noise: 0.1
      process_noise: 0.01
      initial_state_cov: 1.0
      adaptive_noise: true

    # LSTM設定
    lstm:
      sequence_length: 20
      hidden_units: 50
      num_layers: 2
      dropout_rate: 0.2
      attention: true
      bidirectional: false
      epochs: 100
      validation_split: 0.2

    # ハイブリッド設定
    hybrid:
      state_space_weight: 0.3
      lstm_weight: 0.4
      ml_ensemble_weight: 0.3
      adaptive_weighting: true
      regime_detection: true
      uncertainty_quantification: true

  # メタラーニングシステム設定
  meta_learning:
    enabled: true
    repository_size: 100
    lookback_periods: 30

    # モデル工場設定
    model_factory:
      random_forest:
        n_estimators: 100
        max_depth: 10
        min_samples_split: 5
      gradient_boosting:
        n_estimators: 100
        max_depth: 6
        learning_rate: 0.1
        subsample: 0.8
      ridge:
        alpha: 1.0
      lasso:
        alpha: 0.1
        max_iter: 1000
      elastic_net:
        alpha: 0.1
        l1_ratio: 0.5
        max_iter: 1000
      svr:
        kernel: "rbf"
        C: 1.0
        gamma: "scale"
      neural_network:
        hidden_layer_sizes: [100, 50]
        max_iter: 500
        alpha: 0.01

    # 性能追跡設定
    performance_tracking:
      history_length: 50
      comparison_window: 100
      update_frequency: 10
      performance_threshold: 0.8

# アダプターシステム設定
adapter:
  # アダプターモード
  mode: "smart_fallback"  # legacy_only, enhanced_only, ab_test, gradual_rollout, smart_fallback

  # A/Bテスト設定
  ab_test:
    split_ratio: 0.5
    session_tracking: true

  # 段階的移行設定
  gradual_rollout:
    initial_percentage: 0.1
    target_percentage: 1.0
    rollout_steps: 10
    rollout_interval_days: 7

  # 性能比較設定
  performance_comparison:
    enable_metrics: true
    comparison_window: 100
    fallback_threshold: 0.5
    performance_threshold: 0.8
    statistical_significance_required: true

  # ログ・監視設定
  monitoring:
    enable_logging: true
    log_level: "INFO"
    enable_detailed_metrics: true
    save_comparison_data: true
    save_interval_minutes: 60

# 市場状況検出設定
market_regime_detection:
  enabled: true
  lookback_periods: 20

  # ボラティリティ閾値
  volatility_thresholds:
    high: 0.25
    low: 0.10

  # トレンド閾値
  trend_thresholds:
    strong_trend: 0.002  # 0.2%/日

  # 危機検出設定
  crisis_detection:
    consecutive_negative_ratio: 0.7
    min_volatility: 0.25
    min_negative_return: -0.1

  # 回復検出設定
  recovery_detection:
    min_positive_return: 0.05
    min_trend_slope: 0.002
    max_negative_ratio: 0.3

# 性能最適化設定
performance:
  # メモリ管理
  memory:
    max_cache_size: 1000
    cache_ttl_seconds: 3600
    auto_cleanup: true

  # 並列処理
  parallel:
    enable_multiprocessing: true
    max_workers: 4
    chunk_size: 100

  # GPU設定（利用可能な場合）
  gpu:
    enable_gpu: false
    device_id: 0
    memory_growth: true

# セキュリティ設定
security:
  # データ保護
  data_protection:
    encrypt_saved_models: false
    anonymize_logs: true

  # アクセス制御
  access_control:
    require_authentication: false
    api_key_required: false

# 開発・デバッグ設定
development:
  debug_mode: false
  verbose_logging: false
  save_intermediate_results: false
  enable_profiling: false

  # テスト設定
  testing:
    enable_unit_tests: true
    enable_integration_tests: true
    test_data_size: 100
    random_seed: 42