# MLモデル統合システム設定ファイル
# Model Integration System Configuration

# システム統合設定
integration:
  # デフォルトの予測システム
  default_system: "original_system"  # 'original_system' or 'advanced_system'

  # システム切り替え戦略
  fallback_enabled: true              # フォールバック機能の有効化
  performance_based_selection: true   # 性能ベースの自動選択

  # システム間の冷却期間
  switch_cooldown_minutes: 30         # システム切り替え後の冷却期間

# 銘柄別システム優先設定
symbol_preferences:
  # 高ボリューム銘柄 - 高度システム優先
  "7203":  # トヨタ自動車
    preferred_system: "advanced_system"
    confidence_threshold: 0.7
    fallback_allowed: true

  "9984":  # ソフトバンクG
    preferred_system: "advanced_system"
    confidence_threshold: 0.75
    fallback_allowed: true

  "6758":  # ソニー
    preferred_system: "advanced_system"
    confidence_threshold: 0.7
    fallback_allowed: true

  # 中ボリューム銘柄 - 元システム優先
  "8306":  # 三菱UFJ
    preferred_system: "original_system"
    confidence_threshold: 0.6
    fallback_allowed: true

  "4751":  # サイバーエージェント
    preferred_system: "original_system"
    confidence_threshold: 0.65
    fallback_allowed: true

  "7974":  # 任天堂
    preferred_system: "original_system"
    confidence_threshold: 0.6
    fallback_allowed: true

# システム別設定
systems:
  original_system:
    name: "ML Prediction Models"
    description: "オリジナルMLシステム（Random Forest, XGBoost, LightGBM）"
    module: "ml_prediction_models"
    class: "MLPredictionModels"

    # 利用可能なモデルタイプ
    model_types:
      - "RandomForest"
      - "XGBoost"
      - "LightGBM"

    # 予測メソッド設定
    prediction_methods:
      single: "predict"
      ensemble: "predict_ensemble"

    # パフォーマンス期待値
    expected_accuracy: 85.0
    typical_response_time: 0.5  # 秒

  advanced_system:
    name: "Advanced ML Prediction System"
    description: "高度MLシステム（アンサンブル、特徴量選択）"
    module: "advanced_ml_prediction_system"
    class: "AdvancedMLPredictionSystem"

    # 利用可能なモデルタイプ
    model_types:
      - "ensemble_voting"
      - "gradient_boosting"
      - "neural_network"
      - "svm_classifier"

    # 予測メソッド設定
    prediction_methods:
      single: "predict_with_advanced_models"
      ensemble: "predict_ensemble_advanced"

    # パフォーマンス期待値
    expected_accuracy: 90.0
    typical_response_time: 1.2  # 秒

# モデルキャッシュ設定
cache:
  enabled: true                    # キャッシュ機能の有効化
  max_models_in_memory: 10         # メモリ内最大モデル数
  cache_ttl_minutes: 60            # キャッシュ有効期限（分）
  cleanup_interval_minutes: 30     # キャッシュクリーンアップ間隔

  # キャッシュ対象の設定
  cache_targets:
    models: true                   # モデルオブジェクトのキャッシュ
    predictions: false             # 予測結果のキャッシュ（通常は不要）
    metadata: true                 # メタデータのキャッシュ

# パフォーマンス監視設定
monitoring:
  enabled: true                    # パフォーマンス監視の有効化

  # レスポンス時間監視
  response_time:
    warning_threshold: 2.0         # 警告閾値（秒）
    critical_threshold: 5.0        # 緊急閾値（秒）

  # 精度監視
  accuracy:
    minimum_threshold: 70.0        # 最低精度閾値（%）
    warning_threshold: 80.0        # 警告閾値（%）
    target_threshold: 85.0         # 目標閾値（%）

  # エラー率監視
  error_rate:
    warning_threshold: 0.05        # 警告閾値（5%）
    critical_threshold: 0.10       # 緊急閾値（10%）

  # 監視データ保持
  history_retention_days: 30       # 監視データ保持日数

# ロードバランシング設定
load_balancing:
  enabled: false                   # ロードバランシング機能（将来実装）
  strategy: "round_robin"          # 'round_robin', 'performance_based', 'least_loaded'
  health_check_interval: 60        # ヘルスチェック間隔（秒）

# フォールバック設定
fallback:
  enabled: true                    # フォールバック機能の有効化
  max_retries: 2                   # 最大リトライ回数
  retry_delay_seconds: 1           # リトライ間隔（秒）

  # フォールバック順序
  fallback_order:
    - "original_system"
    - "simple_prediction"          # 単純予測（将来実装）

# ログ設定
logging:
  level: "INFO"                    # ログレベル
  performance_logging: true        # パフォーマンスログの有効化
  error_logging: true              # エラーログの有効化
  prediction_logging: false       # 予測ログ（デバッグ用）

# 外部システム連携
integrations:
  # モデル性能監視システム連携
  performance_monitor:
    enabled: true
    notification_threshold: 75.0   # 通知閾値（%）

  # リスク管理システム連携
  risk_manager:
    enabled: true
    risk_adjustment: true          # リスクに基づくシステム選択

  # ダッシュボード連携
  dashboard:
    enabled: false                 # ダッシュボード連携（将来実装）
    real_time_metrics: false       # リアルタイムメトリクス

# 開発・テスト設定
development:
  test_mode: false                 # テストモードの有効化
  mock_predictions: false          # モック予測の使用
  debug_logging: false             # デバッグログの有効化

  # テスト用設定
  test_symbols: ["TEST1", "TEST2"]
  dummy_response_delay: 0.1        # ダミーレスポンス遅延（秒）

# 実験的機能
experimental:
  auto_system_selection: false     # 自動システム選択（将来実装）
  ml_based_routing: false          # ML基盤ルーティング（将来実装）
  adaptive_thresholds: false       # 適応的閾値調整（将来実装）