# SLA Reporter Configuration
# Day Trade ML System - Issue #802

# Prometheus Configuration
prometheus_url: "http://prometheus:9090"

# SLO Configuration Path
slo_config_path: "/app/monitoring/sli_slo/slo_objectives.yaml"

# Output Configuration
output_directory: "/app/monitoring/sla_reporting/reports"

# Services to Monitor
services:
  - "ml-service"
  - "data-service"
  - "symbol-service"
  - "execution-service"
  - "notification-service"

# Email Configuration
smtp:
  smtp_server: "smtp.gmail.com"
  smtp_port: 587
  use_tls: true
  from_email: "sla-reports@day-trade-ml.com"
  username: "${SMTP_USERNAME}"
  password: "${SMTP_PASSWORD}"

# Recipients Configuration
alert_recipients:
  - "oncall@day-trade-ml.com"
  - "platform-team@day-trade-ml.com"

management_recipients:
  - "cto@day-trade-ml.com"
  - "platform-team@day-trade-ml.com"
  - "ml-team@day-trade-ml.com"

weekly_recipients:
  - "management@day-trade-ml.com"
  - "stakeholders@day-trade-ml.com"

# Reporting Schedule
schedule:
  daily_reports:
    enabled: true
    time: "09:00"  # JST
    timezone: "Asia/Tokyo"

  weekly_reports:
    enabled: true
    day: "monday"
    time: "10:00"  # JST
    timezone: "Asia/Tokyo"

  monthly_reports:
    enabled: true
    day: 1  # First day of month
    time: "11:00"  # JST
    timezone: "Asia/Tokyo"

# Alert Thresholds for Auto-reporting
auto_report_triggers:
  compliance_threshold: 95.0  # Send immediate report if compliance < 95%
  error_budget_threshold: 75.0  # Send immediate report if error budget > 75%
  incident_count_threshold: 5  # Send immediate report if incidents > 5

# Report Retention
retention:
  daily_reports: 90  # days
  weekly_reports: 365  # days
  monthly_reports: 1095  # days (3 years)

# Slack Integration (Optional)
slack:
  enabled: true
  webhook_url: "${SLACK_WEBHOOK_URL}"
  channels:
    daily: "#sla-daily"
    weekly: "#sla-weekly"
    alerts: "#sla-alerts"

# Additional Features
features:
  generate_pdf: false  # Requires additional dependencies
  upload_to_s3: false  # Requires AWS configuration
  dashboard_integration: true
  trend_analysis: true
  predictive_alerts: true

# Logging Configuration
logging:
  level: "INFO"
  file: "/app/logs/sla_reporter.log"
  max_size: "100MB"
  backup_count: 5