# .pre-commit-config.yaml
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.15 # Use the latest ruff version
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
  - repo: https://github.com/psf/black
    rev: 24.3.0 # Use the latest black version
    hooks:
      - id: black
        language_version: python3.12 # Should be changed to match your Python version
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0 # Use the latest version
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
