data:
  output_dir: ./data
  default_data_path: dummy_data.csv
strategies:
  default_strategies: ["MA Cross", "RSI", "Sentiment Analysis"]
  ma_cross:
    short_window: 5
    long_window: 25
  rsi:
    window: 14
    overbought_threshold: 70
    oversold_threshold: 30
fetch_data:
  default_ticker: AAPL
  default_tickers: ["AAPL", "MSFT"]
  default_start_date: 2023-01-01
  default_end_date: 2023-01-31
  default_output_path: stock_data.csv
backtest:
  initial_capital: 10000.0
