---
apiVersion: v1
kind: Service
metadata:
  name: kong-gateway-proxy
  namespace: trading-production
  labels:
    app: kong-gateway
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  - port: 443
    targetPort: 8443
    protocol: TCP
    name: https
  selector:
    app: kong-gateway
---
...
