---
apiVersion: v1
kind: Service
metadata:
  name: kong-gateway-admin
  namespace: trading-production
  labels:
    app: kong-gateway
spec:
  type: ClusterIP
  ports:
  - port: 8001
    targetPort: 8001
    protocol: TCP
    name: admin
  selector:
    app: kong-gateway
---
...
