---
# Kong Gateway Routes Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-routes-config
  namespace: trading-production
data:
  kong.yaml: |
    _format_version: "3.0"

    services:
    - name: market-data-service
      url: http://market-data-service.trading-production.svc.cluster.local:80
      plugins:
      - name: rate-limiting
        config:
          minute: 1000
          hour: 10000
      - name: prometheus
        config:
          per_consumer: true
      routes:
      - name: market-data-route
        paths:
        - /api/v1/market
        methods:
        - GET
        - POST

    - name: trading-engine-service
      url: http://trading-engine-service.trading-production.svc.cluster.local:80
      plugins:
      - name: rate-limiting
        config:
          minute: 500
          hour: 5000
      - name: request-size-limiting
        config:
          allowed_payload_size: 1
      routes:
      - name: trading-route
        paths:
        - /api/v1/trading
        methods:
        - GET
        - POST
        - PUT
        - DELETE

    - name: hft-service
      url: http://hft-service.trading-production.svc.cluster.local:80
      plugins:
      - name: rate-limiting
        config:
          minute: 10000
          hour: 100000
      routes:
      - name: hft-route
        paths:
        - /api/v1/hft
        methods:
        - GET
        - POST

    - name: analysis-service
      url: http://analysis-service.trading-production.svc.cluster.local:80
      plugins:
      - name: rate-limiting
        config:
          minute: 200
          hour: 2000
      routes:
      - name: analysis-route
        paths:
        - /api/v1/analysis
        methods:
        - GET
        - POST

    plugins:
    - name: cors
      config:
        origins:
        - http://localhost:3000
        - https://trading-dashboard.example.com
        methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
        headers:
        - Accept
        - Accept-Version
        - Content-Length
        - Content-MD5
        - Content-Type
        - Date
        - X-Auth-Token
        - Authorization
        exposed_headers:
        - X-Auth-Token
        - X-Rate-Limit-Remaining
        credentials: true
        max_age: 3600

    - name: jwt
      config:
        secret_is_base64: false
        claims_to_verify:
        - exp
        - iat
---
...
