name: 'Setup Python Environment'
description: 'Unified Python environment setup with caching and dependency installation'
author: 'day-trade'

inputs:
  python-version:
    description: 'Python version to setup'
    required: false
    default: '3.11'

  cache-version:
    description: 'Cache version for dependency management'
    required: false
    default: 'v4'

  install-dependencies:
    description: 'Whether to install project dependencies'
    required: false
    default: 'true'

  install-dev-dependencies:
    description: 'Whether to install development dependencies'
    required: false
    default: 'true'

  install-test-dependencies:
    description: 'Whether to install test dependencies'
    required: false
    default: 'true'

outputs:
  cache-hit:
    description: 'Whether dependencies were loaded from cache'
    value: ${{ steps.cache-deps.outputs.cache-hit }}

  python-path:
    description: 'Path to Python executable'
    value: ${{ steps.setup-python.outputs.python-path }}

runs:
  using: 'composite'
  steps:
    - name: 🐍 Setup Python ${{ inputs.python-version }}
      id: setup-python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip'

    - name: 📦 Cache dependencies
      id: cache-deps
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pip
          ~/.cache/pre-commit
          ~/.local/share/virtualenvs
          .venv
          __pycache__/
        key: deps-${{ inputs.cache-version }}-${{ runner.os }}-py${{ inputs.python-version }}-${{ hashFiles('**/pyproject.toml', '**/requirements*.txt', '.pre-commit-config.yaml') }}
        restore-keys: |
          deps-${{ inputs.cache-version }}-${{ runner.os }}-py${{ inputs.python-version }}-

    - name: 🔧 Install base dependencies
      if: inputs.install-dependencies == 'true' && steps.cache-deps.outputs.cache-hit != 'true'
      shell: bash
      run: |
        echo "🔧 Installing base dependencies..."
        python -m pip install --upgrade pip wheel setuptools

    - name: 📋 Install project dependencies
      if: inputs.install-dependencies == 'true' && steps.cache-deps.outputs.cache-hit != 'true'
      shell: bash
      run: |
        echo "📋 Installing project dependencies..."
        if [ -f pyproject.toml ]; then
          echo "Found pyproject.toml, installing dependencies..."
          if [ "${{ inputs.install-dev-dependencies }}" = "true" ] && [ "${{ inputs.install-test-dependencies }}" = "true" ]; then
            echo "Installing with dev and test dependencies..."
            pip install -e .[dev,test] || pip install -e . || echo "Base installation failed, continuing..."
          elif [ "${{ inputs.install-dev-dependencies }}" = "true" ]; then
            echo "Installing with dev dependencies..."
            pip install -e .[dev] || pip install -e . || echo "Base installation failed, continuing..."
          elif [ "${{ inputs.install-test-dependencies }}" = "true" ]; then
            echo "Installing with test dependencies..."
            pip install -e .[test] || pip install -e . || echo "Base installation failed, continuing..."
          else
            echo "Installing core package only..."
            pip install -e . || echo "Core installation failed, continuing..."
          fi
        elif [ -f requirements.txt ]; then
          echo "Installing from requirements.txt..."
          pip install -r requirements.txt || echo "Requirements installation failed, continuing..."
        elif [ -f setup.py ]; then
          echo "Installing from setup.py..."
          pip install -e . || echo "Setup.py installation failed, continuing..."
        else
          echo "⚠️ No package configuration found, installing basic tools only"
        fi

    - name: 🧪 Install test dependencies
      if: inputs.install-test-dependencies == 'true' && steps.cache-deps.outputs.cache-hit != 'true'
      shell: bash
      run: |
        echo "🧪 Installing test dependencies..."
        pip install pytest pytest-cov pytest-mock pytest-xdist

    - name: 🔧 Install development tools
      if: inputs.install-dev-dependencies == 'true' && steps.cache-deps.outputs.cache-hit != 'true'
      shell: bash
      run: |
        echo "🔧 Installing development tools..."
        pip install pre-commit black isort ruff mypy

        # pre-commitフックのインストール
        if [ -f .pre-commit-config.yaml ]; then
          pre-commit install-hooks
        fi

    - name: ✅ Verify installation
      shell: bash
      run: |
        echo "✅ Verifying Python environment..."
        python --version || echo "Python version check failed"
        pip --version || echo "Pip version check failed"
        echo "Installed packages:"
        pip list --format=columns | head -20 || echo "Package list failed"

        # パッケージが正しくインストールされているかチェック
        if [ -f pyproject.toml ] || [ -f setup.py ]; then
          python -c "
          try:
              import day_trade
              print('✅ day_trade package import successful')
          except ImportError as e:
              print(f'⚠️ day_trade package import failed: {e}')
              print('This is expected if dependencies are not fully installed')
          except Exception as e:
              print(f'⚠️ Unexpected error: {e}')
              print('This is not critical for CI setup')
          " || echo "Package verification failed, but continuing..."
        else
          echo "No package configuration found, skipping import test"
        fi
