---
# Kong Gateway secrets
apiVersion: v1
kind: Secret
metadata:
  name: kong-secrets
  namespace: trading-production
type: Opaque
stringData:
  postgres-host: "kong-postgres-service"
  postgres-user: "kong"
  postgres-password: "CHANGE_ME_KONG_PASSWORD"
---
