---
# Redis connection secrets
apiVersion: v1
kind: Secret
metadata:
  name: redis-secrets
  namespace: trading-production
type: Opaque
stringData:
  redis-url: "redis://redis-service:6379/0"
  redis-cluster-url: "redis://redis-cluster-service:6379/0"
---
