---
# JWT secrets for authentication
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secrets
  namespace: trading-production
type: Opaque
stringData:
  jwt-secret: "CHANGE_ME_JWT_SECRET_KEY"
  jwt-algorithm: "HS256"
---
