---
# SSL/TLS certificates
apiVersion: v1
kind: Secret
metadata:
  name: tls-secrets
  namespace: trading-production
type: kubernetes.io/tls
data:
  # Base64 encoded certificate and key
  # Replace with actual certificate data
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FUZS0tLS0t...
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0t...
---
