---
# Broker API secrets (for actual trading)
apiVersion: v1
kind: Secret
metadata:
  name: broker-secrets
  namespace: trading-production
type: Opaque
stringData:
  api-key: "CHANGE_ME_BROKER_API_KEY"
  secret-key: "CHANGE_ME_BROKER_SECRET_KEY"
---
