apiVersion: v1
kind: Service
metadata:
  labels:
    app: day-trade-personal
  name: day-trade-personal-service
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: day-trade-personal
  type: ClusterIP
