"""Create all tables

Revision ID: 647bd8b0ed7f
Revises: 659ac11e7009
Create Date: 2025-08-01 12:33:56.303141

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "647bd8b0ed7f"
down_revision = "659ac11e7009"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stocks",
        sa.Column("code", sa.String(length=10), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("market", sa.String(length=20), nullable=True),
        sa.Column("sector", sa.String(length=50), nullable=True),
        sa.Column("industry", sa.String(length=50), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_stock_market", "stocks", ["market"], unique=False)
    op.create_index("idx_stock_sector", "stocks", ["sector"], unique=False)
    op.create_index(op.f("ix_stocks_code"), "stocks", ["code"], unique=True)
    op.create_index(op.f("ix_stocks_id"), "stocks", ["id"], unique=False)
    op.create_table(
        "alerts",
        sa.Column("stock_code", sa.String(length=10), nullable=False),
        sa.Column("alert_type", sa.String(length=20), nullable=False),
        sa.Column("threshold", sa.Float(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("last_triggered", sa.DateTime(), nullable=True),
        sa.Column("memo", sa.String(length=200), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["stock_code"],
            ["stocks.code"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_alert_stock_active", "alerts", ["stock_code", "is_active"], unique=False
    )
    op.create_index("idx_alert_type", "alerts", ["alert_type"], unique=False)
    op.create_index(op.f("ix_alerts_id"), "alerts", ["id"], unique=False)
    op.create_table(
        "price_data",
        sa.Column("stock_code", sa.String(length=10), nullable=False),
        sa.Column("datetime", sa.DateTime(), nullable=False),
        sa.Column("open", sa.Float(), nullable=True),
        sa.Column("high", sa.Float(), nullable=True),
        sa.Column("low", sa.Float(), nullable=True),
        sa.Column("close", sa.Float(), nullable=False),
        sa.Column("volume", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["stock_code"],
            ["stocks.code"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_price_datetime", "price_data", ["datetime"], unique=False)
    op.create_index(
        "idx_price_stock_datetime",
        "price_data",
        ["stock_code", "datetime"],
        unique=True,
    )
    op.create_index(op.f("ix_price_data_id"), "price_data", ["id"], unique=False)
    op.create_table(
        "trades",
        sa.Column("stock_code", sa.String(length=10), nullable=False),
        sa.Column("trade_type", sa.String(length=10), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("commission", sa.Float(), nullable=True),
        sa.Column("trade_datetime", sa.DateTime(), nullable=False),
        sa.Column("memo", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["stock_code"],
            ["stocks.code"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_trade_stock_datetime",
        "trades",
        ["stock_code", "trade_datetime"],
        unique=False,
    )
    op.create_index("idx_trade_type", "trades", ["trade_type"], unique=False)
    op.create_index(op.f("ix_trades_id"), "trades", ["id"], unique=False)
    op.create_table(
        "watchlist_items",
        sa.Column("stock_code", sa.String(length=10), nullable=False),
        sa.Column("group_name", sa.String(length=50), nullable=True),
        sa.Column("memo", sa.String(length=200), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["stock_code"],
            ["stocks.code"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_watchlist_group", "watchlist_items", ["group_name"], unique=False
    )
    op.create_index(
        "idx_watchlist_stock_group",
        "watchlist_items",
        ["stock_code", "group_name"],
        unique=True,
    )
    op.create_index(
        op.f("ix_watchlist_items_id"), "watchlist_items", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_watchlist_items_id"), table_name="watchlist_items")
    op.drop_index("idx_watchlist_stock_group", table_name="watchlist_items")
    op.drop_index("idx_watchlist_group", table_name="watchlist_items")
    op.drop_table("watchlist_items")
    op.drop_index(op.f("ix_trades_id"), table_name="trades")
    op.drop_index("idx_trade_type", table_name="trades")
    op.drop_index("idx_trade_stock_datetime", table_name="trades")
    op.drop_table("trades")
    op.drop_index(op.f("ix_price_data_id"), table_name="price_data")
    op.drop_index("idx_price_stock_datetime", table_name="price_data")
    op.drop_index("idx_price_datetime", table_name="price_data")
    op.drop_table("price_data")
    op.drop_index(op.f("ix_alerts_id"), table_name="alerts")
    op.drop_index("idx_alert_type", table_name="alerts")
    op.drop_index("idx_alert_stock_active", table_name="alerts")
    op.drop_table("alerts")
    op.drop_index(op.f("ix_stocks_id"), table_name="stocks")
    op.drop_index(op.f("ix_stocks_code"), table_name="stocks")
    op.drop_index("idx_stock_sector", table_name="stocks")
    op.drop_index("idx_stock_market", table_name="stocks")
    op.drop_table("stocks")
    # ### end Alembic commands ###
