# Prometheus Configuration for Kong API Gateway
# Day Trade ML System - API Gateway Monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s
  external_labels:
    cluster: 'day-trade-kong'
    environment: 'production'

# Alertmanager Configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Rule Files
rule_files:
  - "rules/*.yml"

# Scrape Configurations
scrape_configs:
  # Kong API Gateway Metrics
  - job_name: 'kong-gateway'
    static_configs:
      - targets: ['kong:8001']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    params:
      format: ['prometheus']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: kong:8001

  # Kong Admin API Metrics
  - job_name: 'kong-admin'
    static_configs:
      - targets: ['kong:8001']
    metrics_path: '/status'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Kong Proxy Metrics via Prometheus Plugin
  - job_name: 'kong-proxy-metrics'
    static_configs:
      - targets: ['kong:8000']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 5s

  # Kong Database (PostgreSQL)
  - job_name: 'kong-postgres'
    static_configs:
      - targets: ['kong-database:5432']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Redis (Rate Limiting & Cache)
  - job_name: 'kong-redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s
    scrape_timeout: 5s

  # Microservices (Backend Services)
  - job_name: 'ml-service'
    static_configs:
      - targets: ['ml-service:8000']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 5s
    relabel_configs:
      - source_labels: [__address__]
        target_label: service_name
        replacement: 'ml-service'

  - job_name: 'data-service'
    static_configs:
      - targets: ['data-service:8001']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 5s
    relabel_configs:
      - source_labels: [__address__]
        target_label: service_name
        replacement: 'data-service'

  - job_name: 'symbol-service'
    static_configs:
      - targets: ['symbol-service:8002']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 5s
    relabel_configs:
      - source_labels: [__address__]
        target_label: service_name
        replacement: 'symbol-service'

  - job_name: 'execution-service'
    static_configs:
      - targets: ['execution-service:8003']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 5s
    relabel_configs:
      - source_labels: [__address__]
        target_label: service_name
        replacement: 'execution-service'

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:8004']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 5s
    relabel_configs:
      - source_labels: [__address__]
        target_label: service_name
        replacement: 'notification-service'

  # Self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

  # Node Exporter (System Metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # cAdvisor (Container Metrics)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s

# Remote Write Configuration (Optional - for long-term storage)
# remote_write:
#   - url: "https://prometheus-remote-write-endpoint"
#     basic_auth:
#       username: "username"
#       password: "password"

# Storage Configuration
storage:
  tsdb:
    retention.time: "30d"
    retention.size: "10GB"
    wal-compression: true