api:
  cors_origins:
  - http://localhost:3000
  - http://localhost:8080
  host: 127.0.0.1
  max_requests_per_worker: 100
  port: 8000
  rate_limit_per_minute: 1000
  ssl_cert_path: null
  ssl_key_path: null
  threads_per_worker: 4
  timeout_seconds: 30
  workers: 1
cache:
  backend: memory
  eviction_policy: allkeys-lru
  host: localhost
  max_memory_mb: 512
  password_env_var: null
  port: 6379
  ttl_seconds: 1800
database:
  connection_pool_size: 5
  connection_timeout: 30
  database: daytrade_dev
  host: localhost
  password_env_var: DB_PASSWORD_DEVELOPMENT
  port: 5432
  query_timeout: 60
  ssl_enabled: false
  username: dev_user
deployment_id: 135121b8
environment: development
monitoring:
  enabled: true
  error_reporting_dsn: null
  jaeger_endpoint: null
  log_format: text
  log_level: DEBUG
  metrics_endpoint: /metrics
  prometheus_port: 9090
optional_env_vars:
- ALPHA_VANTAGE_API_KEY
- QUANDL_API_KEY
- YAHOO_FINANCE_API_KEY
- SMTP_SERVER
- SMTP_USERNAME
- SMTP_PASSWORD
- SLACK_WEBHOOK_URL
- DISCORD_WEBHOOK_URL
performance:
  async_processing: false
  batch_size: 32
  cache_enabled: true
  connection_pooling: true
  gpu_enabled: false
  optimization_level: optimized
  pytorch_enabled: true
  query_caching: false
required_env_vars:
- DB_PASSWORD_DEVELOPMENT
- JWT_SECRET_DEVELOPMENT
- API_KEY_DEVELOPMENT
- ENCRYPTION_KEY_DEVELOPMENT
security:
  allowed_hosts:
  - localhost
  - 127.0.0.1
  api_key_env_var: API_KEY_DEVELOPMENT
  csrf_protection: false
  encryption_key_env_var: ENCRYPTION_KEY_DEVELOPMENT
  jwt_secret_env_var: JWT_SECRET_DEVELOPMENT
  password_policy:
    max_age_days: 365
    min_length: 8
    require_digits: true
    require_lowercase: true
    require_special_chars: false
    require_uppercase: false
  session_timeout_minutes: 120
service_tier: standard
timestamp: '2025-08-09T15:55:37.274323'
version: 1.0.0
