api:
  cors_origins:
  - https://staging.daytrade.com
  host: 0.0.0.0
  max_requests_per_worker: 100
  port: 8080
  rate_limit_per_minute: 500
  ssl_cert_path: null
  ssl_key_path: null
  threads_per_worker: 8
  timeout_seconds: 30
  workers: 2
cache:
  backend: memory
  eviction_policy: allkeys-lru
  host: localhost
  max_memory_mb: 512
  password_env_var: null
  port: 6379
  ttl_seconds: 1800
database:
  connection_pool_size: 10
  connection_timeout: 30
  database: daytrade_staging
  host: staging-db.internal
  password_env_var: DB_PASSWORD_STAGING
  port: 5432
  query_timeout: 60
  ssl_enabled: true
  username: staging_user
deployment_id: bc0e01c8
environment: staging
monitoring:
  enabled: true
  error_reporting_dsn: SENTRY_DSN_STAGING
  jaeger_endpoint: null
  log_format: text
  log_level: DEBUG
  metrics_endpoint: /metrics
  prometheus_port: 9090
optional_env_vars:
- ALPHA_VANTAGE_API_KEY
- QUANDL_API_KEY
- YAHOO_FINANCE_API_KEY
- SMTP_SERVER
- SMTP_USERNAME
- SMTP_PASSWORD
- SLACK_WEBHOOK_URL
- DISCORD_WEBHOOK_URL
performance:
  async_processing: false
  batch_size: 32
  cache_enabled: true
  connection_pooling: true
  gpu_enabled: false
  optimization_level: optimized
  pytorch_enabled: true
  query_caching: true
required_env_vars:
- DB_PASSWORD_STAGING
- JWT_SECRET_STAGING
- API_KEY_STAGING
- ENCRYPTION_KEY_STAGING
security:
  allowed_hosts:
  - staging.daytrade.com
  - staging-api.daytrade.com
  api_key_env_var: API_KEY_STAGING
  csrf_protection: false
  encryption_key_env_var: ENCRYPTION_KEY_STAGING
  jwt_secret_env_var: JWT_SECRET_STAGING
  password_policy:
    max_age_days: 365
    min_length: 8
    require_digits: true
    require_lowercase: true
    require_special_chars: false
    require_uppercase: false
  session_timeout_minutes: 120
service_tier: standard
timestamp: '2025-08-09T15:55:37.343855'
version: 1.0.0
