version: '3.8'

services:
  daytrade-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ENVIRONMENT=staging
      - API_HOST=0.0.0.0
      - API_PORT=8080
      - DB_HOST=staging-db.internal
      - DB_PORT=5432
      - CACHE_HOST=localhost
      - CACHE_PORT=6379
    env_file:
      - .env.staging
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    restart: unless-stopped
    depends_on:
      - database
      - cache

  database:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=daytrade_staging
      - POSTGRES_USER=staging_user
      - POSTGRES_PASSWORD=${DB_PASSWORD_STAGING}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    restart: unless-stopped
    ports:
      - "5432:5432"

  cache:
    image: memcached:alpine

    ports:
      - "6379:6379"
    restart: unless-stopped


volumes:
  postgres_data:
