version: '3.8'

services:
  daytrade-app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - API_HOST=127.0.0.1
      - API_PORT=8000
      - DB_HOST=localhost
      - DB_PORT=5432
      - CACHE_HOST=localhost
      - CACHE_PORT=6379
    env_file:
      - .env.development
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    restart: unless-stopped
    depends_on:
      - database
      - cache

  database:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=daytrade_dev
      - POSTGRES_USER=dev_user
      - POSTGRES_PASSWORD=${DB_PASSWORD_DEVELOPMENT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    restart: unless-stopped
    ports:
      - "5432:5432"

  cache:
    image: memcached:alpine
    
    ports:
      - "6379:6379"
    restart: unless-stopped


volumes:
  postgres_data:
