# Optimization Configuration
# 最適化設定ファイル

# 最適化メソッド設定
optimization_methods:
  grid_search:
    method: "grid"
    cv_folds: 3
    max_iterations: 50
    scoring: "accuracy"
    n_jobs: -1
    random_state: 42
    enabled: true

  random_search:
    method: "random"
    cv_folds: 3
    max_iterations: 100
    scoring: "accuracy"
    n_jobs: -1
    random_state: 42
    enabled: true

  bayesian_optimization:
    method: "bayesian"
    cv_folds: 3
    max_iterations: 50
    scoring: "accuracy"
    n_jobs: -1
    random_state: 42
    enabled: false  # scikit-optimizeが必要

# タスク別スコアリング設定
task_scoring:
  price_direction:
    primary: "accuracy"
    secondary: ["f1_weighted", "precision_weighted", "recall_weighted"]

  price_regression:
    primary: "r2"
    secondary: ["neg_mean_squared_error", "neg_mean_absolute_error"]

# パフォーマンス設定
performance:
  # 並列処理設定
  n_jobs_default: -1
  n_jobs_conservative: 4

  # メモリ使用量制限
  memory_limit_gb: 8

  # タイムアウト設定（秒）
  optimization_timeout: 3600  # 1時間
  model_fit_timeout: 300      # 5分

# ログ設定
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  optimization_progress: true
  parameter_details: false

# 結果保存設定
storage:
  # データベース設定
  database_path: "hyperparameter_optimization/optimization_results.db"

  # キャッシュ設定
  enable_cache: true
  cache_max_entries: 1000

  # 結果エクスポート
  export_best_params: true
  export_detailed_results: false

# 高度な設定
advanced:
  # Early stopping設定
  early_stopping:
    enabled: true
    patience: 10
    min_improvement: 0.001

  # パラメータ空間制限
  parameter_space_limiting:
    enabled: true
    max_combinations_grid: 100
    max_values_per_param: 4

  # 分散最適化（将来拡張用）
  distributed:
    enabled: false
    workers: 4