# 銘柄選択システム設定ファイル
# Symbol Selection System Configuration

# 基本設定
system:
  log_level: INFO
  db_path: "data/topix500_master.db"
  cache_timeout_minutes: 30

# デフォルト選択基準
default_criteria:
  min_market_cap: 100000000000    # 1000億円以上
  max_market_cap: null            # 上限なし
  min_liquidity_score: 0.5        # 流動性スコア
  max_symbols: 50                 # 最大銘柄数
  excluded_sectors: []            # 除外セクター
  preferred_sectors: []           # 優先セクター

# 取引戦略別設定
strategies:
  # 高流動性銘柄（デイトレード向け）
  liquid_trading:
    min_market_cap: 300000000000  # 3000億円以上
    max_symbols: 20
    excluded_sectors: ["REIT", "ETF"]
    priority_weight: "market_cap_times_weight"

  # 高ボラティリティ銘柄
  volatile_trading:
    min_market_cap: 50000000000   # 500億円以上
    max_market_cap: 1000000000000 # 1兆円以下
    max_symbols: 10
    preferred_sectors: ["情報・通信業", "サービス業", "電気機器"]
    volatility_threshold: 0.3

  # バランス型ポートフォリオ
  balanced_portfolio:
    min_market_cap: 200000000000  # 2000億円以上
    max_symbols: 15
    excluded_sectors: ["REIT", "ETF", "その他金融業"]
    diversification_factor: 0.7

# セクター分散設定
sector_diversification:
  enabled: true
  max_symbols_per_sector: 2       # セクター当たり最大銘柄数
  min_sectors: 5                  # 最小セクター数
  market_cap_threshold: 100000000000  # 1000億円以上

# クエリ構築設定
query_builder:
  default_sort: "market_cap_desc"
  allowed_sorts:
    - "market_cap_desc"
    - "topix_weight_desc"
    - "combined_score_desc"
  default_filters:
    - "is_active = TRUE"

# エラーハンドリング設定
error_handling:
  max_retries: 3
  retry_delay_seconds: 1
  fallback_to_defaults: true
  log_all_errors: true

# パフォーマンス設定
performance:
  connection_pool_size: 5
  query_timeout_seconds: 30
  enable_query_cache: true
  cache_size_mb: 50