# Issue #800 Phase 3: Day Trade ML System Helm Chart

apiVersion: v2
name: day-trade-ml
description: Day Trade ML System - EnsembleSystem (93%精度) + 完全自動化
type: application
version: 1.0.0
appVersion: "1.0.0"

keywords:
  - machine-learning
  - trading
  - ensemble
  - automation
  - 93-percent-accuracy

home: https://github.com/your-org/day-trade
sources:
  - https://github.com/your-org/day-trade

maintainers:
  - name: Development Team
    email: dev-team@company.com

dependencies:
  - name: postgresql
    version: 12.8.5
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled

  - name: redis
    version: 17.11.7
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled

  - name: prometheus
    version: 23.1.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: monitoring.prometheus.enabled

  - name: grafana
    version: 6.58.7
    repository: https://grafana.github.io/helm-charts
    condition: monitoring.grafana.enabled

annotations:
  category: Machine Learning
  licenses: MIT
  images: |
    - name: ml-service
      image: ghcr.io/your-org/day-trade/ml-service:1.0.0
    - name: data-service
      image: ghcr.io/your-org/day-trade/data-service:1.0.0
    - name: scheduler-service
      image: ghcr.io/your-org/day-trade/scheduler-service:1.0.0