# Issue #800 Phase 3: Data Service Kubernetes マニフェスト
# DataFetcher + SmartSymbolSelector + リアルタイムデータパイプライン

apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-service
  namespace: day-trade
  labels:
    app: data-service
    component: data-pipeline
    version: v1
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: data-service
  template:
    metadata:
      labels:
        app: data-service
        component: data-pipeline
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8001"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: day-trade-data-service
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
      containers:
      - name: data-service
        image: ghcr.io/your-org/day-trade/data-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8001
          name: http
          protocol: TCP
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: DATA_CACHE_PATH
          value: "/app/data"
        - name: LOG_LEVEL
          value: "WARNING"
        - name: PYTHONUNBUFFERED
          value: "1"
        envFrom:
        - secretRef:
            name: data-service-secrets
        - configMapRef:
            name: data-service-config
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 45
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 9
        volumeMounts:
        - name: data-cache
          mountPath: /app/data
        - name: logs
          mountPath: /app/logs
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL
      volumes:
      - name: data-cache
        persistentVolumeClaim:
          claimName: data-cache-pvc
      - name: logs
        emptyDir: {}
      imagePullSecrets:
      - name: ghcr-secret
      nodeSelector:
        kubernetes.io/os: linux

---
apiVersion: v1
kind: Service
metadata:
  name: data-service
  namespace: day-trade
  labels:
    app: data-service
    component: data-pipeline
spec:
  type: ClusterIP
  ports:
  - port: 8001
    targetPort: 8001
    protocol: TCP
    name: http
  selector:
    app: data-service

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: day-trade-data-service
  namespace: day-trade
  labels:
    app: data-service
    component: data-pipeline

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: data-service-config
  namespace: day-trade
  labels:
    app: data-service
    component: data-pipeline
data:
  MARKET_HOURS_TIMEZONE: "Asia/Tokyo"
  TRADING_HOURS_START: "09:00"
  TRADING_HOURS_END: "15:00"
  CACHE_TTL_SECONDS: "300"
  DATA_REFRESH_INTERVAL_MINUTES: "5"
  SYMBOL_SELECTION_CRITERIA: "liquidity,volatility,market_cap"
  MAX_SYMBOLS_PER_REQUEST: "50"
  ENABLE_REAL_TIME_DATA: "true"
  ENABLE_SMART_SYMBOL_SELECTION: "true"

---
apiVersion: v1
kind: Secret
metadata:
  name: data-service-secrets
  namespace: day-trade
  labels:
    app: data-service
    component: data-pipeline
type: Opaque
stringData:
  DATABASE_URL: "postgresql://user:password@postgres:5432/day_trade"
  REDIS_URL: "redis://:password@redis:6379"
  MARKET_DATA_API_KEY: "your-market-data-api-key-here"
  YAHOO_FINANCE_API_KEY: "your-yahoo-finance-api-key-here"
  ALPHA_VANTAGE_API_KEY: "your-alpha-vantage-api-key-here"

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: data-service-hpa
  namespace: day-trade
  labels:
    app: data-service
    component: data-pipeline
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: data-service
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 600
      policies:
      - type: Percent
        value: 25
        periodSeconds: 60