# Day Trade Personal GitLab CI/CD

stages:
  - test
  - security
  - build
  - deploy

variables:
  DOCKER_REGISTRY: registry.gitlab.com
  DOCKER_IMAGE: $DOCKER_REGISTRY/$CI_PROJECT_PATH
  PYTHON_VERSION: "3.11"

# Cache pip dependencies
cache:
  paths:
    - ~/.cache/pip/

before_script:
  - python --version
  - pip install --upgrade pip

# テストステージ
test:
  stage: test
  image: python:3.11
  services:
    - postgres:15
  variables:
    POSTGRES_DB: test_db
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    DATABASE_URL: postgresql://postgres:postgres@postgres:5432/test_db
  script:
    - pip install -r requirements.txt
    - pip install pytest pytest-cov
    - python -m pytest --cov=. --cov-report=term --cov-report=xml
  coverage: '/TOTAL.*\s+(\d+%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
  only:
    - main
    - develop
    - merge_requests

# セキュリティスキャン
security_scan:
  stage: security
  image: python:3.11
  script:
    - pip install -r requirements.txt
    - python security_assessment.py
  artifacts:
    reports:
      sast: data/security_report_*.html
  only:
    - main
    - develop

# Dockerイメージビルド
build:
  stage: build
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $DOCKER_IMAGE:$CI_COMMIT_SHA .
    - docker build -t $DOCKER_IMAGE:latest .
    - docker push $DOCKER_IMAGE:$CI_COMMIT_SHA
    - docker push $DOCKER_IMAGE:latest
  only:
    - main

# ステージング環境デプロイ
deploy_staging:
  stage: deploy
  image: alpine/helm:latest
  script:
    - echo "Deploy to staging"
    - helm upgrade --install day-trade-personal-staging ./helm/day-trade-personal --set image.tag=$CI_COMMIT_SHA
  environment:
    name: staging
    url: https://day-trade-personal-staging.example.com
  only:
    - develop

# 本番環境デプロイ
deploy_production:
  stage: deploy
  image: alpine/helm:latest
  script:
    - echo "Deploy to production"
    - helm upgrade --install day-trade-personal ./helm/day-trade-personal --set image.tag=$CI_COMMIT_SHA
  environment:
    name: production
    url: https://day-trade-personal.example.com
  when: manual
  only:
    - main
