apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: day-trade-personal
    version: 1.0.0
  name: day-trade-personal-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: day-trade-personal
  template:
    metadata:
      labels:
        app: day-trade-personal
        version: 1.0.0
    spec:
      containers:
      - env:
        - name: FLASK_ENV
          value: production
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              key: database-url
              name: day-trade-personal-secrets
        image: day-trade-personal:1.0.0
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        name: day-trade-personal
        ports:
        - containerPort: 8000
          name: http
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 512Mi
