# マルチタイムフレーム予測システム設定
# Issue #882対応：デイトレード以外の取引機能

# 基本設定
system_name: "マルチタイムフレーム予測システム"
version: "1.0.0"
debug_mode: false

# 予測タイムフレーム設定
timeframes:
  # デイトレード（既存）
  daily:
    name: "デイトレード"
    prediction_horizon_days: 1
    data_period: "1y"
    min_training_samples: 100
    enabled: true
    description: "翌日の価格変動予測（既存機能）"

  # 週間予測
  weekly:
    name: "週間予測"
    prediction_horizon_days: 7
    data_period: "2y"
    min_training_samples: 200
    enabled: true
    description: "1週間後の価格変動予測"

  # 月間予測
  monthly:
    name: "月間予測"
    prediction_horizon_days: 30
    data_period: "5y"
    min_training_samples: 300
    enabled: true
    description: "1ヶ月後の価格変動予測"

  # 四半期予測
  quarterly:
    name: "四半期予測"
    prediction_horizon_days: 90
    data_period: "10y"
    min_training_samples: 500
    enabled: false  # オプション機能
    description: "3ヶ月後の価格変動予測"

# 予測タスク設定（タイムフレーム別）
prediction_tasks:
  daily:
    price_direction:
      enabled: true
      threshold_percent: 1.0  # 1%以上の変動で方向判定
      classes: ["下落", "横ばい", "上昇"]
      weight: 1.0

    volatility:
      enabled: true
      target_type: "regression"
      weight: 0.8

    momentum_strength:
      enabled: true
      threshold_percent: 2.0  # 2%以上でstrong判定
      classes: ["弱い", "中程度", "強い"]
      weight: 0.7

  weekly:
    price_direction:
      enabled: true
      threshold_percent: 3.0  # 週間では3%以上で方向判定
      classes: ["下落", "横ばい", "上昇"]
      weight: 1.0

    trend_continuation:
      enabled: true
      lookback_days: 7
      classes: ["反転", "継続", "加速"]
      weight: 0.9

    volatility:
      enabled: true
      target_type: "regression"
      weight: 0.6

  monthly:
    price_direction:
      enabled: true
      threshold_percent: 5.0  # 月間では5%以上で方向判定
      classes: ["大幅下落", "下落", "横ばい", "上昇", "大幅上昇"]
      weight: 1.0

    trend_strength:
      enabled: true
      classes: ["弱いトレンド", "中程度", "強いトレンド"]
      weight: 0.8

    market_regime:
      enabled: true
      classes: ["ベア相場", "レンジ相場", "ブル相場"]
      weight: 0.7

# 特徴量設定（タイムフレーム別）
feature_engineering:
  daily:
    # 短期特徴量
    price_features:
      sma_periods: [5, 10, 20, 50]
      ema_periods: [5, 12, 26]
      bollinger_periods: [20]
      price_ratios: true

    technical_indicators:
      rsi_period: 14
      macd_params: [12, 26, 9]
      stochastic_params: [14, 3, 3]
      momentum_periods: [5, 10]

    volume_features:
      volume_sma_periods: [10, 20]
      volume_ratios: true
      vwap: true

    pattern_features:
      candlestick_patterns: true
      gap_analysis: true
      support_resistance: false  # 計算負荷高

  weekly:
    # 中期特徴量
    price_features:
      sma_periods: [10, 20, 50, 100, 200]
      ema_periods: [12, 26, 50]
      bollinger_periods: [20, 50]
      price_ratios: true

    technical_indicators:
      rsi_period: 14
      macd_params: [12, 26, 9]
      stochastic_params: [14, 3, 3]
      adx_period: 14
      atr_period: 14

    volume_features:
      volume_sma_periods: [20, 50]
      volume_ratios: true
      vwap: true
      accumulation_distribution: true

    trend_features:
      trend_strength_periods: [20, 50]
      breakout_detection: true
      channel_analysis: true

  monthly:
    # 長期特徴量
    price_features:
      sma_periods: [20, 50, 100, 200]
      ema_periods: [20, 50, 100]
      bollinger_periods: [20, 50]
      fibonacci_levels: true

    technical_indicators:
      rsi_period: 14
      macd_params: [12, 26, 9]
      atr_period: 20
      williams_r_period: 14

    macro_features:
      sector_relative_strength: true
      market_correlation: true
      volatility_regime: true

    fundamental_proxy:
      price_to_sma_ratios: [50, 100, 200]
      momentum_persistence: true

# モデル設定（タイムフレーム別）
models:
  daily:
    random_forest:
      n_estimators: 200
      max_depth: 15
      min_samples_split: 10
      class_weight: "balanced"

    xgboost:
      n_estimators: 300
      max_depth: 8
      learning_rate: 0.1
      subsample: 0.8

    lightgbm:
      n_estimators: 200
      max_depth: 10
      learning_rate: 0.1

  weekly:
    random_forest:
      n_estimators: 300
      max_depth: 20
      min_samples_split: 15
      class_weight: "balanced"

    xgboost:
      n_estimators: 400
      max_depth: 10
      learning_rate: 0.08
      subsample: 0.85

    lightgbm:
      n_estimators: 300
      max_depth: 12
      learning_rate: 0.08

  monthly:
    random_forest:
      n_estimators: 400
      max_depth: 25
      min_samples_split: 20
      class_weight: "balanced"

    xgboost:
      n_estimators: 500
      max_depth: 12
      learning_rate: 0.05
      subsample: 0.9

    lightgbm:
      n_estimators: 400
      max_depth: 15
      learning_rate: 0.05

# アンサンブル設定
ensemble:
  # タイムフレーム内アンサンブル
  intra_timeframe:
    method: "weighted_voting"  # weighted_voting, stacking
    weight_calculation: "performance_based"
    minimum_models: 2

  # タイムフレーム間統合
  inter_timeframe:
    enabled: true
    method: "hierarchical"  # hierarchical, independent
    weight_by_horizon: true
    consistency_check: true

  # 信頼度計算
  confidence_calculation:
    consensus_weight: 0.4
    individual_confidence_weight: 0.3
    historical_accuracy_weight: 0.3
    minimum_confidence_threshold: 0.5

# 訓練設定
training:
  # データ分割
  train_test_split:
    test_size: 0.2
    validation_size: 0.1
    time_aware_split: true

  # クロスバリデーション
  cross_validation:
    method: "TimeSeriesSplit"
    n_splits: 5
    gap_days: 5  # テストセット前のギャップ

  # ハイパーパラメータ最適化
  hyperparameter_optimization:
    enabled: false  # 計算負荷のため初期は無効
    method: "RandomizedSearchCV"
    n_iter: 50
    cv_folds: 3

  # 定期再訓練
  retraining:
    enabled: true
    frequency_days: 30
    performance_threshold: 0.1  # 性能低下10%で再訓練
    minimum_new_samples: 20

# 評価設定
evaluation:
  # 評価指標
  metrics:
    classification:
      - accuracy
      - precision
      - recall
      - f1_score
      - roc_auc
      - cohen_kappa

    regression:
      - mse
      - mae
      - r2
      - mape

  # ベンチマーク比較
  benchmarks:
    random_baseline: true
    buy_and_hold: true
    sma_crossover: true
    previous_trend: true

  # 実績評価
  backtesting:
    enabled: true
    lookback_periods: [30, 90, 180, 365]
    walk_forward_analysis: true

# データ管理
data_management:
  # キャッシュ設定
  caching:
    feature_cache_days: 7
    model_cache_days: 30
    prediction_cache_hours: 6

  # データ品質
  data_quality:
    missing_data_threshold: 0.1
    outlier_detection: true
    data_consistency_check: true

  # ストレージ
  storage:
    database_path: "multi_timeframe_predictions.db"
    model_storage_path: "models/multi_timeframe"
    backup_enabled: true
    retention_days: 365

# パフォーマンス最適化
performance:
  # 並列処理
  parallel_processing:
    max_workers: 4
    chunk_size: 100
    memory_limit_mb: 1000

  # メモリ管理
  memory_management:
    feature_batch_size: 1000
    model_memory_limit_mb: 500
    garbage_collection: true

# ログ設定
logging:
  level: "INFO"
  detailed_training_logs: true
  prediction_logs: true
  performance_logs: true

  log_files:
    training: "logs/multi_timeframe_training.log"
    predictions: "logs/multi_timeframe_predictions.log"
    performance: "logs/multi_timeframe_performance.log"

# 統合設定
integration:
  # 既存システム連携
  existing_systems:
    ml_prediction_models: true
    enhanced_feature_engineering: true
    real_data_provider: true
    prediction_accuracy_enhancer: true

  # API設定
  api_integration:
    rest_endpoints: true
    real_time_predictions: true
    batch_predictions: true

  # 通知設定
  notifications:
    prediction_alerts: true
    model_performance_alerts: true
    system_status_alerts: true

# 実験的機能
experimental:
  features:
    # 深層学習モデル
    deep_learning:
      enabled: false
      lstm_enabled: false
      transformer_enabled: false

    # 強化学習
    reinforcement_learning:
      enabled: false
      environment_simulation: false

    # 外部データ統合
    external_data:
      news_sentiment: false
      social_media_sentiment: false
      economic_indicators: false

    # 自動特徴量生成
    automated_feature_engineering:
      enabled: false
      genetic_programming: false
      neural_architecture_search: false