"""create_initial_schema

Revision ID: d013b997ab84
Revises: 
Create Date: 2025-08-18 07:03:56.517491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd013b997ab84'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """マイグレーション適用"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sample_price_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_code', sa.String(length=10), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sample_stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('market', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('stocks',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('market', sa.String(length=20), nullable=True),
    sa.Column('sector', sa.String(length=50), nullable=True),
    sa.Column('industry', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_stock_code_name', 'stocks', ['code', 'name'], unique=False)
    op.create_index('idx_stock_market', 'stocks', ['market'], unique=False)
    op.create_index('idx_stock_sector', 'stocks', ['sector'], unique=False)
    op.create_index(op.f('ix_stocks_code'), 'stocks', ['code'], unique=True)
    op.create_index(op.f('ix_stocks_id'), 'stocks', ['id'], unique=False)
    op.create_table('alerts',
    sa.Column('stock_code', sa.String(length=10), nullable=False),
    sa.Column('alert_type', sa.Enum('PRICE_ABOVE', 'PRICE_BELOW', 'CHANGE_PERCENT_UP', 'CHANGE_PERCENT_DOWN', 'VOLUME_SPIKE', 'RSI_OVERBOUGHT', 'RSI_OVERSOLD', 'MACD_SIGNAL', 'BOLLINGER_BREAKOUT', 'PATTERN_DETECTED', 'CUSTOM_CONDITION', name='alerttype'), nullable=False),
    sa.Column('threshold', sa.DECIMAL(precision=10, scale=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_triggered', sa.DateTime(), nullable=True),
    sa.Column('memo', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['stock_code'], ['stocks.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alert_stock_active', 'alerts', ['stock_code', 'is_active'], unique=False)
    op.create_index('idx_alert_type', 'alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_table('price_data',
    sa.Column('stock_code', sa.String(length=10), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('open', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('high', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('low', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('close', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['stock_code'], ['stocks.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_price_datetime', 'price_data', ['datetime'], unique=False)
    op.create_index('idx_price_datetime_desc', 'price_data', ['datetime'], unique=False)
    op.create_index('idx_price_stock_close', 'price_data', ['stock_code', 'close'], unique=False)
    op.create_index('idx_price_stock_datetime', 'price_data', ['stock_code', 'datetime'], unique=True)
    op.create_index('idx_price_volume', 'price_data', ['volume'], unique=False)
    op.create_index(op.f('ix_price_data_id'), 'price_data', ['id'], unique=False)
    op.create_table('trades',
    sa.Column('stock_code', sa.String(length=10), nullable=False),
    sa.Column('trade_type', sa.Enum('BUY', 'SELL', name='tradetype'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('commission', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('trade_datetime', sa.DateTime(), nullable=False),
    sa.Column('memo', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['stock_code'], ['stocks.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_trade_datetime_desc', 'trades', ['trade_datetime'], unique=False)
    op.create_index('idx_trade_price', 'trades', ['price'], unique=False)
    op.create_index('idx_trade_stock_datetime', 'trades', ['stock_code', 'trade_datetime'], unique=False)
    op.create_index('idx_trade_stock_type', 'trades', ['stock_code', 'trade_type'], unique=False)
    op.create_index('idx_trade_type', 'trades', ['trade_type'], unique=False)
    op.create_index(op.f('ix_trades_id'), 'trades', ['id'], unique=False)
    op.create_table('watchlist_items',
    sa.Column('stock_code', sa.String(length=10), nullable=False),
    sa.Column('group_name', sa.String(length=50), nullable=True),
    sa.Column('memo', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['stock_code'], ['stocks.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_watchlist_group', 'watchlist_items', ['group_name'], unique=False)
    op.create_index('idx_watchlist_stock_group', 'watchlist_items', ['stock_code', 'group_name'], unique=True)
    op.create_index(op.f('ix_watchlist_items_id'), 'watchlist_items', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """マイグレーション取り消し"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watchlist_items_id'), table_name='watchlist_items')
    op.drop_index('idx_watchlist_stock_group', table_name='watchlist_items')
    op.drop_index('idx_watchlist_group', table_name='watchlist_items')
    op.drop_table('watchlist_items')
    op.drop_index(op.f('ix_trades_id'), table_name='trades')
    op.drop_index('idx_trade_type', table_name='trades')
    op.drop_index('idx_trade_stock_type', table_name='trades')
    op.drop_index('idx_trade_stock_datetime', table_name='trades')
    op.drop_index('idx_trade_price', table_name='trades')
    op.drop_index('idx_trade_datetime_desc', table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_price_data_id'), table_name='price_data')
    op.drop_index('idx_price_volume', table_name='price_data')
    op.drop_index('idx_price_stock_datetime', table_name='price_data')
    op.drop_index('idx_price_stock_close', table_name='price_data')
    op.drop_index('idx_price_datetime_desc', table_name='price_data')
    op.drop_index('idx_price_datetime', table_name='price_data')
    op.drop_table('price_data')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_index('idx_alert_type', table_name='alerts')
    op.drop_index('idx_alert_stock_active', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_stocks_id'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_code'), table_name='stocks')
    op.drop_index('idx_stock_sector', table_name='stocks')
    op.drop_index('idx_stock_market', table_name='stocks')
    op.drop_index('idx_stock_code_name', table_name='stocks')
    op.drop_table('stocks')
    op.drop_table('sample_stocks')
    op.drop_table('sample_price_data')
    # ### end Alembic commands ###