# Boatrace競艇予想システム設定ファイル

# APIクライアント設定
api:
  base_url: "https://boatraceopenapi.github.io"
  timeout: 30
  max_retries: 3
  backoff_factor: 0.3
  cache_enabled: true
  cache_dir: "data/cache"
  
# データベース設定
database:
  url: "sqlite:///data/databases/boatrace.db"
  echo: false
  pool_pre_ping: true
  
# データ収集設定
data_collection:
  auto_collect: true
  collect_interval: 3600  # 1時間ごと
  max_date_range: 30      # 最大30日分
  skip_existing: true
  
# 予想エンジン設定
prediction:
  engine_name: "BoatracePredictor"
  engine_version: "1.0.0"
  min_confidence: 0.3
  max_predictions_per_day: 100
  
  # 重み付け設定
  weights:
    racer_class: 0.25
    winning_rate: 0.20
    stadium_affinity: 0.15
    boat_number: 0.15
    recent_form: 0.15
    motor_boat: 0.10
    
# 投票戦略設定
betting:
  default_strategy: "balanced"
  max_bet_ratio: 0.05      # 資金の5%まで
  min_bet_amount: 100      # 最小100円
  max_bet_amount: 50000    # 最大5万円
  
  # 戦略別設定
  strategies:
    conservative:
      risk_level: "low"
      main_bet_types: ["win", "quinella"]
      max_bet_ratio: 0.03
      
    balanced:
      risk_level: "medium"
      main_bet_types: ["win", "exacta", "quinella", "trio"]
      max_bet_ratio: 0.05
      
    aggressive:
      risk_level: "high"
      main_bet_types: ["trifecta", "exacta"]
      max_bet_ratio: 0.08
      
# ポートフォリオ管理設定
portfolio:
  initial_capital: 100000  # 初期資金10万円
  risk_free_rate: 0.001    # リスクフリーレート0.1%
  max_drawdown_limit: 0.20 # 最大ドローダウン20%
  
  # アラート設定
  alerts:
    daily_loss_limit: 10000    # 日次損失限界1万円
    weekly_loss_limit: 50000   # 週次損失限界5万円
    roi_threshold: -10.0       # ROI-10%でアラート
    
# ログ設定
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  max_file_size: 10485760    # 10MB
  backup_count: 5
  
  loggers:
    api_client: "DEBUG"
    prediction_engine: "INFO"
    betting_system: "INFO"
    
# 競技場設定
stadiums:
  # 注目競技場（デフォルト分析対象）
  featured:
    - 3   # 江戸川
    - 11  # びわこ  
    - 12  # 住之江
    - 17  # 宮島
    
  # 分析除外競技場
  excluded: []
  
  # 特別条件設定
  special_conditions:
    windy_stadiums: [6, 11, 23]      # 風の影響が大きい
    tidal_stadiums: [3, 4, 7, 8, 9, 12, 13, 14, 15, 16, 17, 18, 19, 20, 22, 23]  # 潮汐影響
    
# パフォーマンス設定
performance:
  cache_size: 1000
  max_concurrent_predictions: 5
  batch_size: 100
  
# セキュリティ設定
security:
  mask_sensitive_data: true
  log_personal_info: false
  encrypt_database: false
  
# 拡張機能設定
features:
  web_dashboard: false      # Webダッシュボード（今後実装）
  mobile_api: false         # モバイルAPI（今後実装）
  real_time_updates: false  # リアルタイム更新（今後実装）
  auto_betting: false       # 自動投票（今後実装）