# Data Sources Configuration for real_data_provider_v2.py
# Issue #853対応：データソースの管理と設定の外部化

data_sources:
  yahoo_finance:
    enabled: true
    priority: 1
    timeout: 30
    rate_limit_per_minute: 100
    rate_limit_per_day: 1000
    quality_threshold: 80.0
    max_price_threshold: 1000000

  stooq:
    enabled: true
    priority: 2
    timeout: 20
    base_url: "https://stooq.com/q/d/l/"
    rate_limit_per_minute: 60
    rate_limit_per_day: 500
    quality_threshold: 70.0

  alpha_vantage:
    enabled: false
    priority: 3
    timeout: 30
    api_key: ""
    base_url: "https://www.alphavantage.co/query"
    rate_limit_per_minute: 5
    rate_limit_per_day: 500
    quality_threshold: 90.0

  mock:
    enabled: true
    priority: 99
    timeout: 1
    quality_threshold: 50.0