# Hyperparameter Spaces Configuration
# ハイパーパラメータ空間設定

# Random Forest分類器のハイパーパラメータ空間
random_forest_classifier:
  n_estimators: [100, 200, 300, 500]
  max_depth: [10, 15, 20, 25, null]
  min_samples_split: [2, 5, 10]
  min_samples_leaf: [1, 2, 4]
  max_features: ["sqrt", "log2", 0.3, 0.5]
  class_weight: ["balanced", "balanced_subsample", null]
  bootstrap: [true, false]

# Random Forest回帰器のハイパーパラメータ空間
random_forest_regressor:
  n_estimators: [100, 200, 300, 500]
  max_depth: [10, 15, 20, 25, null]
  min_samples_split: [2, 5, 10]
  min_samples_leaf: [1, 2, 4]
  max_features: ["sqrt", "log2", 0.3, 0.5]
  bootstrap: [true, false]

# XGBoost分類器のハイパーパラメータ空間
xgboost_classifier:
  n_estimators: [100, 200, 300, 500]
  max_depth: [3, 5, 7, 10]
  learning_rate: [0.01, 0.05, 0.1, 0.2]
  subsample: [0.6, 0.7, 0.8, 0.9, 1.0]
  colsample_bytree: [0.6, 0.7, 0.8, 0.9, 1.0]
  gamma: [0, 0.1, 0.2, 0.5]
  reg_alpha: [0, 0.1, 0.5, 1.0]
  reg_lambda: [0, 0.1, 0.5, 1.0]

# XGBoost回帰器のハイパーパラメータ空間
xgboost_regressor:
  n_estimators: [100, 200, 300, 500]
  max_depth: [3, 5, 7, 10]
  learning_rate: [0.01, 0.05, 0.1, 0.2]
  subsample: [0.6, 0.7, 0.8, 0.9, 1.0]
  colsample_bytree: [0.6, 0.7, 0.8, 0.9, 1.0]
  gamma: [0, 0.1, 0.2, 0.5]
  reg_alpha: [0, 0.1, 0.5, 1.0]
  reg_lambda: [0, 0.1, 0.5, 1.0]

# LightGBM分類器のハイパーパラメータ空間（将来拡張用）
lightgbm_classifier:
  n_estimators: [100, 200, 300, 500]
  max_depth: [3, 5, 7, 10]
  learning_rate: [0.01, 0.05, 0.1, 0.2]
  subsample: [0.6, 0.7, 0.8, 0.9, 1.0]
  colsample_bytree: [0.6, 0.7, 0.8, 0.9, 1.0]
  reg_alpha: [0, 0.1, 0.5, 1.0]
  reg_lambda: [0, 0.1, 0.5, 1.0]

# LightGBM回帰器のハイパーパラメータ空間（将来拡張用）
lightgbm_regressor:
  n_estimators: [100, 200, 300, 500]
  max_depth: [3, 5, 7, 10]
  learning_rate: [0.01, 0.05, 0.1, 0.2]
  subsample: [0.6, 0.7, 0.8, 0.9, 1.0]
  colsample_bytree: [0.6, 0.7, 0.8, 0.9, 1.0]
  reg_alpha: [0, 0.1, 0.5, 1.0]
  reg_lambda: [0, 0.1, 0.5, 1.0]

# 最適化設定
optimization_settings:
  # Random Search用設定
  random_search:
    n_iter_default: 100
    n_iter_quick: 50
    n_iter_extensive: 200

  # Grid Search用設定
  grid_search:
    max_combinations: 50
    max_values_per_param: 3

  # Bayesian Optimization用設定
  bayesian_optimization:
    n_iter_default: 50
    n_iter_quick: 25
    n_iter_extensive: 100
    acquisition_function: "gp_hedge"

# タスク別デフォルトベースラインスコア
baseline_scores:
  classification:
    accuracy: 0.5
    f1: 0.3
    precision: 0.4
    recall: 0.4

  regression:
    r2: 0.0
    mse: 1.0
    rmse: 1.0
    mae: 1.0