# ハイパーパラメータ空間定義 - Issue #856対応
# 各モデルのハイパーパラメータ探索範囲を外部化

# RandomForest 分類用パラメータ
random_forest_classifier:
  n_estimators: [100, 200, 300, 500]
  max_depth: [10, 15, 20, 25, null]
  min_samples_split: [2, 5, 10]
  min_samples_leaf: [1, 2, 4]
  max_features: ['sqrt', 'log2', null]
  bootstrap: [true, false]
  class_weight: [null, 'balanced']

# RandomForest 回帰用パラメータ
random_forest_regressor:
  n_estimators: [100, 200, 300, 500]
  max_depth: [10, 15, 20, 25, null]
  min_samples_split: [2, 5, 10]
  min_samples_leaf: [1, 2, 4]
  max_features: ['sqrt', 'log2', null]
  bootstrap: [true, false]

# XGBoost 分類用パラメータ
xgboost_classifier:
  n_estimators: [100, 200, 300, 500]
  max_depth: [3, 5, 7, 10]
  learning_rate: [0.01, 0.05, 0.1, 0.2]
  subsample: [0.8, 0.9, 1.0]
  colsample_bytree: [0.8, 0.9, 1.0]
  reg_alpha: [0, 0.1, 0.5, 1.0]
  reg_lambda: [0, 0.1, 0.5, 1.0]

# XGBoost 回帰用パラメータ
xgboost_regressor:
  n_estimators: [100, 200, 300, 500]
  max_depth: [3, 5, 7, 10]
  learning_rate: [0.01, 0.05, 0.1, 0.2]
  subsample: [0.8, 0.9, 1.0]
  colsample_bytree: [0.8, 0.9, 1.0]
  reg_alpha: [0, 0.1, 0.5, 1.0]
  reg_lambda: [0, 0.1, 0.5, 1.0]

# 最適化設定
optimization_settings:
  # Grid Search設定
  grid_search:
    cv_folds: 3
    max_iterations: 50
    n_jobs: -1
    verbose: 1

  # Random Search設定
  random_search:
    cv_folds: 3
    n_iter: 100  # RandomizedSearchCVで使用
    max_iterations: 100
    n_jobs: -1
    verbose: 1

  # Bayesian最適化設定
  bayesian_optimization:
    cv_folds: 3
    n_iter: 50
    max_iterations: 50
    n_jobs: -1
    verbose: 1

# ベースラインスコア設定
baseline_scores:
  # 分類タスク
  classification:
    accuracy: 0.5  # ランダム予測レベル
    precision: 0.5
    recall: 0.5
    f1: 0.5

  # 回帰タスク
  regression:
    r2: 0.0       # 平均値予測レベル
    mse: 1.0      # データ依存
    mae: 1.0      # データ依存
    rmse: 1.0     # データ依存

# パラメータ重要度分析設定
importance_analysis:
  enabled: true
  methods:
    - cv_variance      # CV結果の分散分析
    - correlation      # パラメータと性能の相関
    - permutation      # パーミュテーション重要度

  # 分析対象パラメータ
  focus_parameters:
    - n_estimators
    - max_depth
    - learning_rate
    - min_samples_split

# システム設定
system:
  log_level: INFO
  cache_results: true
  save_models: true
  random_state: 42