special_holidays:
  - date: 2024-12-31
    name: 大納会翌日
  - date: 2025-01-01
    name: 元日
  - date: 2025-01-02
    name: 年始休場
  - date: 2025-01-03
    name: 年始休場
special_trading_days:
  - date: 2025-01-04
    name: 臨時営業日
