# Model Performance Monitor Thresholds
# モデル性能監視の閾値設定

performance_thresholds:
  # 精度閾値 (0-100の範囲)
  accuracy: 90.0

  # 予測精度の最小要求値
  prediction_accuracy: 85.0

  # リターン予測の閾値
  return_prediction: 75.0

  # ボラティリティ予測の閾値
  volatility_prediction: 80.0

# 監視対象銘柄の設定
monitoring:
  # デフォルト監視銘柄
  default_symbols:
    - "7203"  # トヨタ
    - "8306"  # 三菱UFJ
    - "4751"  # サイバーエージェント
    - "6098"  # リクルート
    - "9984"  # ソフトバンク

  # バリデーション時間（時間）
  validation_hours: 168  # 7日間

  # 最小評価サンプル数
  min_samples: 10

# 再学習トリガーの設定
retraining:
  # 段階的再学習の設定
  granular_mode: true

  # 銘柄別再学習の閾値
  symbol_specific_threshold: 80.0

  # 全体的再学習の閾値
  global_threshold: 85.0

  # 再学習の冷却期間（時間）
  cooldown_hours: 24

# システム設定
system:
  # ログレベル
  log_level: "INFO"

  # データベースパス
  database_path: "ml_models_data/upgrade_system.db"

  # バックアップ閾値データ
  backup_enabled: true