# MLモデル性能監視システム設定
# Issue #857対応：性能閾値の外部化と柔軟化

# システム基本設定
system:
  name: "MLモデル性能監視システム"
  version: "1.0.0"
  enabled: true
  debug_mode: false

# 性能閾値設定
performance_thresholds:
  # 精度関連閾値
  accuracy:
    minimum_threshold: 0.75        # 最低精度閾値 75%
    warning_threshold: 0.80        # 警告閾値 80%
    target_threshold: 0.90         # 目標閾値 90%
    critical_threshold: 0.70       # 緊急閾値 70%

  # 予測精度の最小要求値
  prediction_accuracy: 85.0

  # リターン予測の閾値
  return_prediction: 75.0

  # 回帰タスク用閾値
  r2_score:
    minimum_threshold: 0.60        # 最低R²閾値 60%
    warning_threshold: 0.70        # 警告閾値 70%
    target_threshold: 0.85         # 目標閾値 85%
    critical_threshold: 0.50       # 緊急閾値 50%

  # 損失関数閾値
  loss_functions:
    mse:
      maximum_threshold: 0.10      # MSE最大閾値
      warning_threshold: 0.08      # MSE警告閾値
    mae:
      maximum_threshold: 0.05      # MAE最大閾値
      warning_threshold: 0.04      # MAE警告閾値

  # ビジネス指標閾値
  business_metrics:
    win_rate:
      minimum_threshold: 0.55      # 勝率最低閾値 55%
      target_threshold: 0.70       # 勝率目標閾値 70%
    profit_loss_ratio:
      minimum_threshold: 1.2       # 損益比最低閾値 1.2
      target_threshold: 2.0        # 損益比目標閾値 2.0
    sharpe_ratio:
      minimum_threshold: 0.5       # シャープレシオ最低閾値
      target_threshold: 1.5        # シャープレシオ目標閾値

# アラート設定
alerts:
  # 性能劣化アラート
  performance_degradation:
    enabled: true
    check_interval_minutes: 15
    consecutive_failures_threshold: 3
    notification_methods: ["log", "file"]

  # 異常検知アラート
  anomaly_detection:
    enabled: true
    z_score_threshold: 2.5
    sliding_window_size: 20
    min_samples_for_detection: 10

  # 重要度別設定
  severity_levels:
    critical:
      accuracy_drop: 0.10          # 10%以上の精度低下
      consecutive_failures: 5
      immediate_notification: true
    warning:
      accuracy_drop: 0.05          # 5%以上の精度低下
      consecutive_failures: 3
      immediate_notification: false
    info:
      accuracy_drop: 0.02          # 2%以上の精度低下
      consecutive_failures: 2
      immediate_notification: false

# 再訓練設定
retraining:
  # 自動再訓練トリガー
  auto_trigger:
    enabled: true
    performance_drop_threshold: 0.05  # 5%性能低下で再訓練
    time_based_interval_days: 30      # 30日間隔での定期再訓練
    data_drift_threshold: 0.15        # データドリフト閾値

  # 再訓練戦略
  strategy:
    incremental_learning: true        # 増分学習の使用
    full_retrain_threshold: 0.10      # 10%性能低下で完全再訓練
    minimum_new_samples: 100          # 最小新サンプル数
    validation_split: 0.2             # 検証用データ分割比

  # 再訓練スケジューラー
  scheduler:
    business_hours_only: true         # 営業時間のみ実行
    max_concurrent_retraining: 2      # 同時再訓練最大数
    priority_queue: true              # 優先度キューの使用

# モデル別設定
model_specific:
  # Random Forest設定
  RandomForest:
    performance_weight: 1.0
    retraining_priority: 2

  # XGBoost設定
  XGBoost:
    performance_weight: 1.2
    retraining_priority: 1

  # LightGBM設定
  LightGBM:
    performance_weight: 1.1
    retraining_priority: 1

# 評価指標設定
metrics:
  # 分類タスク指標
  classification:
    primary: "accuracy"
    secondary: ["precision", "recall", "f1_score"]
    advanced: ["roc_auc", "cohen_kappa"]

  # 回帰タスク指標
  regression:
    primary: "r2_score"
    secondary: ["mse", "mae"]
    advanced: ["mape", "explained_variance"]

  # カスタム指標
  custom:
    profit_loss_ratio: true
    win_rate: true
    sharpe_ratio: true
    maximum_drawdown: true

# データベース設定
database:
  # 性能データ保存設定
  performance_table: "model_performance_history"
  alerts_table: "performance_alerts"
  retraining_table: "retraining_history"

  # 接続設定
  connection:
    type: "sqlite"
    path: "data/model_performance.db"
    timeout: 30

# ログ設定
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  files:
    performance: "logs/model_performance.log"
    alerts: "logs/performance_alerts.log"
    retraining: "logs/model_retraining.log"

# 統合設定
integration:
  # 既存システム連携
  ml_prediction_models: true
  enhanced_feature_engineering: true
  real_data_provider: true

  # 通知システム連携
  notification_endpoints:
    webhook_url: null
    email_notifications: false
    slack_integration: false

  # ダッシュボード連携
  dashboard_integration:
    enabled: true
    update_interval_seconds: 30
    metrics_endpoint: "/api/performance/metrics"

# A/Bテスト
ab_testing:
  enabled: false
  control_group_ratio: 0.5
  test_duration_days: 7

# 実験的機能
experimental_features:
  # 自動ハイパーパラメータ調整
  auto_hyperparameter_tuning:
    enabled: false
    optimization_method: "bayesian"
    max_trials: 50

  # フェデレーション学習
  federated_learning:
    enabled: false
    aggregation_method: "fedavg"

  # モデル解釈性
  explainability:
    enabled: true
    shap_analysis: true
    feature_importance: true
    lime_analysis: false