
default_profile: Moderate

profiles:
  Conservative:
    # 資金管理
    total_capital: 1000000
    max_position_size: 0.05  # 5%
    max_daily_loss: 0.03     # 3%
    max_loss_per_trade: 0.01  # 1%

    # デイトレード設定
    max_positions: 2
    max_holding_time: 180  # 3時間
    force_close_time: "14:45"

    # リスク調整
    volatility_multiplier: 1.2
    news_risk_reduction: 0.3

    # アラート設定
    loss_alert_threshold: -0.005  # -0.5%
    time_alert_threshold: 120    # 2時間

  Moderate:
    # 資金管理
    total_capital: 1000000
    max_position_size: 0.10  # 10%
    max_daily_loss: 0.05     # 5%
    max_loss_per_trade: 0.02  # 2%

    # デイトレード設定
    max_positions: 3
    max_holding_time: 240  # 4時間
    force_close_time: "14:50"

    # リスク調整
    volatility_multiplier: 1.5
    news_risk_reduction: 0.5

    # アラート設定
    loss_alert_threshold: -0.01  # -1%
    time_alert_threshold: 180    # 3時間

  Aggressive:
    # 資金管理
    total_capital: 1000000
    max_position_size: 0.15  # 15%
    max_daily_loss: 0.07     # 7%
    max_loss_per_trade: 0.03  # 3%

    # デイトレード設定
    max_positions: 5
    max_holding_time: 300  # 5時間
    force_close_time: "14:55"

    # リスク調整
    volatility_multiplier: 2.0
    news_risk_reduction: 0.7

    # アラート設定
    loss_alert_threshold: -0.015 # -1.5%
    time_alert_threshold: 240    # 4時間
