# システム統合設定
# Issue #870統合システムとレガシーシステムの統合設定

system_integration:
  # 統合モード
  integration_mode: "hybrid"  # legacy, enhanced, hybrid, auto

  # システム優先順位
  system_priority:
    - "enhanced_prediction"
    - "legacy_ml"
    - "fallback"

  # フォールバック設定
  fallback:
    enable_fallback: true
    fallback_timeout_seconds: 30
    max_retry_attempts: 3
    retry_delay_seconds: 1

  # 互換性設定
  compatibility:
    maintain_legacy_api: true
    enable_legacy_warnings: true
    deprecation_warnings: true

# 予測システム統合
prediction_systems:
  # 拡張予測システム
  enhanced:
    enabled: true
    config_file: "enhanced_prediction.yaml"
    priority: 1

  # レガシーML予測システム
  legacy_ml:
    enabled: true
    fallback_role: true
    priority: 2

  # 基本予測システム
  basic:
    enabled: true
    emergency_fallback: true
    priority: 3

# データプロバイダー統合
data_providers:
  # リアルデータプロバイダー
  real_data:
    enabled: true
    priority: 1
    cache_enabled: true

  # YFinanceプロバイダー
  yfinance:
    enabled: true
    priority: 2
    fallback_role: true

  # モックデータプロバイダー
  mock_data:
    enabled: true
    emergency_fallback: true
    priority: 3

# 分析エンジン統合
analysis_engines:
  # 拡張分析エンジン
  enhanced_analysis:
    enabled: true
    config_file: "enhanced_prediction.yaml"

  # 技術指標分析
  technical_indicators:
    enabled: true
    consolidated_system: true

  # ポートフォリオ分析
  portfolio_analysis:
    enabled: true
    integration_mode: "unified"

# トレードエンジン統合
trading_engines:
  # パーソナルデイトレードエンジン
  personal_day_trading:
    enabled: true
    enhanced_prediction_integration: true

  # HFTエンジン（利用可能な場合）
  hft_engine:
    enabled: false
    integration_mode: "optional"

# 通知システム統合
notification_systems:
  # リアルタイム通知
  realtime_alerts:
    enabled: true
    enhanced_predictions: true

  # ダッシュボード通知
  dashboard_notifications:
    enabled: true
    integration_mode: "unified"

# キャッシュシステム統合
cache_systems:
  # 分散キャッシュ
  distributed_cache:
    enabled: true
    integration_mode: "unified"

  # データキャッシュ
  data_cache:
    enabled: true
    enhanced_features: true

# 監視システム統合
monitoring_systems:
  # 性能監視
  performance_monitoring:
    enabled: true
    enhanced_metrics: true

  # セキュリティ監視
  security_monitoring:
    enabled: true
    integration_alerts: true

# API統合
api_integration:
  # REST API
  rest_api:
    enabled: true
    enhanced_endpoints: true
    legacy_compatibility: true

  # WebSocket API
  websocket_api:
    enabled: false
    realtime_predictions: true

# データベース統合
database_integration:
  # 最適化データベース
  optimized_database:
    enabled: true
    enhanced_features: true

  # パフォーマンス追跡
  performance_tracking:
    enabled: true
    enhanced_metrics: true

# 設定管理
configuration_management:
  # 設定ファイル統合
  config_files:
    base_config: "settings.json"
    enhanced_config: "enhanced_prediction.yaml"
    integration_config: "system_integration.yaml"

  # 環境別設定
  environment_configs:
    development:
      debug_mode: true
      verbose_logging: true
      enable_testing: true
    production:
      debug_mode: false
      verbose_logging: false
      enable_optimization: true
    staging:
      debug_mode: false
      verbose_logging: true
      enable_testing: true

# ログ統合設定
logging_integration:
  # 統合ログ設定
  unified_logging:
    enabled: true
    log_level: "INFO"
    log_format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

  # コンポーネント別ログ
  component_logging:
    enhanced_prediction: "INFO"
    legacy_systems: "WARNING"
    integration_layer: "INFO"

  # ログ出力先
  log_outputs:
    console: true
    file: true
    rotating_file: true
    max_file_size_mb: 10
    backup_count: 5

# 移行設定
migration_settings:
  # 段階的移行
  gradual_migration:
    enabled: true
    migration_phases:
      - phase: "pilot"
        percentage: 10
        duration_days: 7
      - phase: "partial"
        percentage: 50
        duration_days: 14
      - phase: "full"
        percentage: 100
        duration_days: 30

  # バックアップ設定
  backup:
    enable_backup: true
    backup_interval_hours: 24
    retention_days: 30

  # ロールバック設定
  rollback:
    enable_rollback: true
    rollback_timeout_minutes: 30
    auto_rollback_on_error: true

# 品質保証
quality_assurance:
  # テスト統合
  testing:
    enable_unit_tests: true
    enable_integration_tests: true
    enable_performance_tests: true
    test_coverage_threshold: 80

  # 品質ゲート
  quality_gates:
    performance_threshold: 0.8
    error_rate_threshold: 0.05
    response_time_threshold_ms: 1000

  # 監視・アラート
  monitoring:
    enable_health_checks: true
    health_check_interval_seconds: 60
    alert_on_failure: true
    alert_threshold_failures: 3

# ドキュメント統合
documentation:
  # API ドキュメント
  api_docs:
    enabled: true
    auto_generation: true
    include_examples: true

  # ユーザーマニュアル
  user_manual:
    enabled: true
    include_migration_guide: true
    include_troubleshooting: true

  # 開発者ガイド
  developer_guide:
    enabled: true
    include_architecture: true
    include_integration_examples: true