database:
  echo: false
  max_overflow: 10
  pool_pre_ping: true
  pool_recycle: 3600
  pool_size: 5
  pool_timeout: 30
  ssl_mode: disable
  url: sqlite:///./test_production.db
monitoring:
  connection_pool_warning_threshold: 0.8
  slow_query_threshold_ms: 1000
