# Issue #800 Phase 4: Prometheus本番環境設定
# EnsembleSystem (93%精度) + 完全自動化システム監視

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s
  external_labels:
    cluster: 'day-trade-production'
    environment: 'production'
    project: 'day-trade'

# ルールファイル
rule_files:
  - "rules/*.yml"

# アラートマネージャー設定
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093
      scheme: http
      timeout: 10s
      api_version: v2

# スクレイプ設定
scrape_configs:
  # Prometheus自身の監視
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: /metrics

  # MLサービス監視 (EnsembleSystem 93%精度)
  - job_name: 'ml-service'
    static_configs:
      - targets: ['ml-service:8000']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s
    honor_labels: true
    params:
      format: ['prometheus']
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'ml_.*'
        target_label: service
        replacement: 'ml-service'

  # データサービス監視 (DataFetcher + SmartSymbolSelector)
  - job_name: 'data-service'
    static_configs:
      - targets: ['data-service:8001']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'data_.*'
        target_label: service
        replacement: 'data-service'

  # スケジューラサービス監視 (ExecutionScheduler)
  - job_name: 'scheduler-service'
    static_configs:
      - targets: ['scheduler-service:8002']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'scheduler_.*'
        target_label: service
        replacement: 'scheduler-service'

  # Redis監視
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s
    metrics_path: /metrics

  # PostgreSQL監視
  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s
    metrics_path: /metrics

  # Node Exporter (システムメトリクス)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s
    metrics_path: /metrics

  # cAdvisor (コンテナメトリクス)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s
    metrics_path: /metrics