version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: day-trade-personal:1.0.0
    container_name: day-trade-personal-app
    restart: unless-stopped
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/daytradedb
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=your-secret-key-here
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    networks:
      - daytrade-network
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  db:
    image: postgres:15-alpine
    container_name: day-trade-personal-db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=daytradedb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - daytrade-network

  redis:
    image: redis:7-alpine
    container_name: day-trade-personal-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - daytrade-network
    command: redis-server --appendonly yes

  nginx:
    image: nginx:alpine
    container_name: day-trade-personal-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - ./static:/var/www/static
    depends_on:
      - app
    networks:
      - daytrade-network

volumes:
  postgres_data:
  redis_data:

networks:
  daytrade-network:
    driver: bridge
