# Issue #800 Phase 1: Prometheus設定
# 開発環境用メトリクス収集設定

global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus自身の監視
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # MLサービス監視
  - job_name: 'ml-service'
    static_configs:
      - targets: ['ml-service:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # データサービス監視
  - job_name: 'data-service'
    static_configs:
      - targets: ['data-service:8001']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # スケジューラサービス監視
  - job_name: 'scheduler-service'
    static_configs:
      - targets: ['scheduler-service:8002']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Redis監視
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  # PostgreSQL監視
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']