# Grafana データソース設定
# Prometheus統合設定

apiVersion: 1

datasources:
  # メインPrometheusデータソース
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      queryTimeout: '60s'
      timeInterval: '15s'

  # 高頻度メトリクス用Prometheus（1秒間隔）
  - name: Prometheus-HighFreq
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: false
    editable: false
    jsonData:
      httpMethod: POST
      queryTimeout: '30s'
      timeInterval: '1s'

  # AlertManager統合
  - name: AlertManager
    type: alertmanager
    access: proxy
    url: http://alertmanager:9093
    isDefault: false
    editable: false
    jsonData:
      implementation: prometheus
