---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: analysis-models-pvc
  namespace: trading-production
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: fast-ssd
---
