apiVersion: apps/v1
kind: Deployment
metadata:
  name: analysis-service
  namespace: trading-production
  labels:
    app: analysis-service
    version: v1.0
    component: analysis
spec:
  replicas: 2
  selector:
    matchLabels:
      app: analysis-service
  template:
    metadata:
      labels:
        app: analysis-service
        version: v1.0
    spec:
      containers:
      - name: analysis-service
        image: day-trade/analysis-service:v1.0
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: postgresql-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: redis-secrets
              key: redis-url
        - name: ML_MODEL_PATH
          value: "/app/models"
        - name: GPU_ENABLED
          value: "false"  # GPU使用可能な場合は"true"に変更
        resources:
          requests:
            cpu: 1000m
            memory: 2Gi
          limits:
            cpu: 2000m
            memory: 4Gi
            # GPU使用時は以下のコメントアウト解除
            # nvidia.com/gpu: 1
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
        - name: model-storage
          mountPath: /app/models
      volumes:
      - name: config-volume
        configMap:
          name: analysis-config
      - name: model-storage
        persistentVolumeClaim:
          claimName: analysis-models-pvc
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - analysis-service
              topologyKey: kubernetes.io/hostname

---
apiVersion: v1
kind: Service
metadata:
  name: analysis-service
  namespace: trading-production
  labels:
    app: analysis-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: analysis-service

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: analysis-models-pvc
  namespace: trading-production
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: fast-ssd

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: analysis-config
  namespace: trading-production
data:
  config.yaml: |
    server:
      host: "0.0.0.0"
      port: 8080

    analysis:
      technical_indicators:
        - sma
        - ema
        - rsi
        - macd
        - bollinger_bands
        - stochastic

      ml_models:
        ensemble_enabled: true
        model_types:
          - random_forest
          - gradient_boosting
          - neural_network

        prediction_horizon: 60  # minutes
        feature_window: 1440    # minutes (24 hours)

      performance:
        batch_size: 1000
        parallel_processing: true
        cache_predictions: true
        prediction_ttl: 300  # seconds

    database:
      connection_pool_size: 10
      query_timeout: 30

    cache:
      analysis_result_ttl: 300
      ml_prediction_ttl: 600
      technical_indicator_ttl: 60

    logging:
      level: "INFO"
      format: "json"
