---
apiVersion: v1
kind: Service
metadata:
  name: trading-engine-service
  namespace: trading-production
  labels:
    app: trading-engine-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: trading-engine-service
---
...
