---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trading-engine-service
  namespace: trading-production
  labels:
    app: trading-engine-service
    version: v1.0
    component: trading
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trading-engine-service
  template:
    metadata:
      labels:
        app: trading-engine-service
        version: v1.0
    spec:
      containers:
      - name: trading-engine-service
        image: day-trade/trading-engine-service:v1.0
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: postgresql-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: redis-secrets
              key: redis-url
        - name: BROKER_API_KEY
          valueFrom:
            secretKeyRef:
              name: broker-secrets
              key: api-key
        - name: RISK_LIMIT_PERCENT
          value: "10"
        resources:
          requests:
            cpu: 1000m
            memory: 1Gi
          limits:
            cpu: 1500m
            memory: 2Gi
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
      volumes:
      - name: config-volume
        configMap:
          name: trading-engine-config
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - trading-engine-service
            topologyKey: kubernetes.io/hostname
---
...
