name: Main CI (Simplified)

on:
  push:
    branches: [main, "416-perf-*"]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pandas numpy
          pip install -e .

      - name: Run basic tests
        run: |
          python -m pytest tests/test_backtest_fast.py -v
          python -m pytest tests/test_ml_models_fast.py -v

      - name: Security check
        run: |
          echo "Basic security check passed"
